# [CK__SVIEN__NAM__267ABA7A]

In [0]:
USE [QLSVien]
GO

In [0]:
ALTER TABLE [dbo].[SVIEN] DROP CONSTRAINT [CK__SVIEN__NAM__267ABA7A]
GO

# [CK__KQUA__DIEM__32E0915F]

In [0]:
ALTER TABLE [dbo].[KQUA] DROP CONSTRAINT [CK__KQUA__DIEM__32E0915F]
GO

# [FK_SVIEN_MAKHOA]

In [0]:
ALTER TABLE [dbo].[SVIEN] DROP CONSTRAINT [FK_SVIEN_MAKHOA]
GO

# [FK_MHOC_MAKH]

In [0]:
ALTER TABLE [dbo].[MHOC] DROP CONSTRAINT [FK_MHOC_MAKH]
GO

# [FK_KQUA_MASV]

In [0]:
ALTER TABLE [dbo].[KQUA] DROP CONSTRAINT [FK_KQUA_MASV]
GO

# [FK_KQUA_MAHP]

In [0]:
ALTER TABLE [dbo].[KQUA] DROP CONSTRAINT [FK_KQUA_MAHP]
GO

# [FK_HPHAN_MAMH]

In [0]:
ALTER TABLE [dbo].[HPHAN] DROP CONSTRAINT [FK_HPHAN_MAMH]
GO

# [FK_DKIEN_MAMH]

In [0]:
ALTER TABLE [dbo].[DKIEN] DROP CONSTRAINT [FK_DKIEN_MAMH]
GO

# [dbo].[SVIEN]

In [0]:
/****** Object:  Table [dbo].[SVIEN]    Script Date: 10/24/2021 3:27:08 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SVIEN]') AND type in (N'U'))
DROP TABLE [dbo].[SVIEN]
GO

# [dbo].[MHOC]

In [0]:
/****** Object:  Table [dbo].[MHOC]    Script Date: 10/24/2021 3:27:08 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MHOC]') AND type in (N'U'))
DROP TABLE [dbo].[MHOC]
GO

# [dbo].[KQUA]

In [0]:
/****** Object:  Table [dbo].[KQUA]    Script Date: 10/24/2021 3:27:08 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[KQUA]') AND type in (N'U'))
DROP TABLE [dbo].[KQUA]
GO

# [dbo].[KHOA]

In [0]:
/****** Object:  Table [dbo].[KHOA]    Script Date: 10/24/2021 3:27:08 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[KHOA]') AND type in (N'U'))
DROP TABLE [dbo].[KHOA]
GO

# [dbo].[HPHAN]

In [0]:
/****** Object:  Table [dbo].[HPHAN]    Script Date: 10/24/2021 3:27:08 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[HPHAN]') AND type in (N'U'))
DROP TABLE [dbo].[HPHAN]
GO

# [dbo].[DKIEN]

In [0]:
/****** Object:  Table [dbo].[DKIEN]    Script Date: 10/24/2021 3:27:08 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DKIEN]') AND type in (N'U'))
DROP TABLE [dbo].[DKIEN]
GO

# [QLSVien]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [QLSVien]    Script Date: 10/24/2021 3:27:08 PM ******/
DROP DATABASE [QLSVien]
GO

In [0]:
/****** Object:  Database [QLSVien]    Script Date: 10/24/2021 3:27:08 PM ******/
CREATE DATABASE [QLSVien]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLSVien', FILENAME = N'/var/opt/mssql/data/QLSVien.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLSVien_log', FILENAME = N'/var/opt/mssql/data/QLSVien_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [QLSVien] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLSVien].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QLSVien] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QLSVien] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QLSVien] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QLSVien] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QLSVien] SET ARITHABORT OFF 
GO
ALTER DATABASE [QLSVien] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QLSVien] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QLSVien] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QLSVien] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QLSVien] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QLSVien] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QLSVien] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QLSVien] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QLSVien] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QLSVien] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QLSVien] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QLSVien] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QLSVien] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QLSVien] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QLSVien] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QLSVien] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QLSVien] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QLSVien] SET RECOVERY FULL 
GO
ALTER DATABASE [QLSVien] SET  MULTI_USER 
GO
ALTER DATABASE [QLSVien] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QLSVien] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QLSVien] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QLSVien] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QLSVien] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QLSVien] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'QLSVien', N'ON'
GO
ALTER DATABASE [QLSVien] SET QUERY_STORE = OFF
GO

# [dbo].[DKIEN]

In [0]:
USE [QLSVien]
GO

In [0]:
/****** Object:  Table [dbo].[DKIEN]    Script Date: 10/24/2021 3:27:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DKIEN](
	[MAMH] [varchar](8) NOT NULL,
	[MAMH_TRUOC] [varchar](8) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MAMH] ASC,
	[MAMH_TRUOC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[HPHAN]

In [0]:
/****** Object:  Table [dbo].[HPHAN]    Script Date: 10/24/2021 3:27:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HPHAN](
	[MAHP] [int] NOT NULL,
	[MAMH] [varchar](8) NOT NULL,
	[HOCKI] [int] NULL,
	[NAM] [int] NULL,
	[GV] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[MAHP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[KHOA]

In [0]:
/****** Object:  Table [dbo].[KHOA]    Script Date: 10/24/2021 3:27:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHOA](
	[MAKHOA] [varchar](4) NOT NULL,
	[TENKHOA] [varchar](30) NOT NULL,
	[NAMTHANHLAP] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MAKHOA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[KQUA]

In [0]:
/****** Object:  Table [dbo].[KQUA]    Script Date: 10/24/2021 3:27:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KQUA](
	[MASV] [int] NOT NULL,
	[MAHP] [int] NOT NULL,
	[DIEM] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[MASV] ASC,
	[MAHP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[MHOC]

In [0]:
/****** Object:  Table [dbo].[MHOC]    Script Date: 10/24/2021 3:27:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MHOC](
	[TENMH] [varchar](30) NOT NULL,
	[MAMH] [varchar](8) NOT NULL,
	[TINCHI] [int] NULL,
	[MAKH] [varchar](4) NULL,
PRIMARY KEY CLUSTERED 
(
	[MAMH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[SVIEN]

In [0]:
/****** Object:  Table [dbo].[SVIEN]    Script Date: 10/24/2021 3:27:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SVIEN](
	[TEN] [varchar](30) NOT NULL,
	[MASV] [int] NOT NULL,
	[NAM] [int] NULL,
	[MAKH] [varchar](4) NOT NULL,
	[NAMSINH] [date] NULL,
	[GIOITINH] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[MASV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[HPHAN]

In [0]:
INSERT [dbo].[HPHAN] ([MAHP], [MAMH], [HOCKI], [NAM], [GV]) VALUES (1, N'cad101', 1, 2011, N'Toan')
INSERT [dbo].[HPHAN] ([MAHP], [MAMH], [HOCKI], [NAM], [GV]) VALUES (2, N'cad101', 2, 2011, N'Van')
INSERT [dbo].[HPHAN] ([MAHP], [MAMH], [HOCKI], [NAM], [GV]) VALUES (3, N'cad101', 3, 2011, N'Anh')
INSERT [dbo].[HPHAN] ([MAHP], [MAMH], [HOCKI], [NAM], [GV]) VALUES (4, N'cad101', 4, 2011, N'Hung')
INSERT [dbo].[HPHAN] ([MAHP], [MAMH], [HOCKI], [NAM], [GV]) VALUES (5, N'Cad100', 1, 2012, N'Anh')
INSERT [dbo].[HPHAN] ([MAHP], [MAMH], [HOCKI], [NAM], [GV]) VALUES (6, N'Cad100', 2, 2012, N'Van')
INSERT [dbo].[HPHAN] ([MAHP], [MAMH], [HOCKI], [NAM], [GV]) VALUES (7, N'Cad100', 3, 2012, N'Anh')
INSERT [dbo].[HPHAN] ([MAHP], [MAMH], [HOCKI], [NAM], [GV]) VALUES (8, N'Cad100', 4, 2012, N'Toan')
GO

# [dbo].[KHOA]

In [0]:
INSERT [dbo].[KHOA] ([MAKHOA], [TENKHOA], [NAMTHANHLAP]) VALUES (N'1', N'K14', 2018)
INSERT [dbo].[KHOA] ([MAKHOA], [TENKHOA], [NAMTHANHLAP]) VALUES (N'2', N'K15', 2019)
INSERT [dbo].[KHOA] ([MAKHOA], [TENKHOA], [NAMTHANHLAP]) VALUES (N'3', N'K16', 2020)
INSERT [dbo].[KHOA] ([MAKHOA], [TENKHOA], [NAMTHANHLAP]) VALUES (N'4', N'K17', 2021)
GO

# [dbo].[KQUA]

In [0]:
INSERT [dbo].[KQUA] ([MASV], [MAHP], [DIEM]) VALUES (123456, 2, 5)
INSERT [dbo].[KQUA] ([MASV], [MAHP], [DIEM]) VALUES (123456, 3, 7)
INSERT [dbo].[KQUA] ([MASV], [MAHP], [DIEM]) VALUES (123456, 4, 8)
INSERT [dbo].[KQUA] ([MASV], [MAHP], [DIEM]) VALUES (123456, 8, 9)
INSERT [dbo].[KQUA] ([MASV], [MAHP], [DIEM]) VALUES (130303, 1, 1)
INSERT [dbo].[KQUA] ([MASV], [MAHP], [DIEM]) VALUES (130303, 2, 2)
INSERT [dbo].[KQUA] ([MASV], [MAHP], [DIEM]) VALUES (130303, 3, 3)
INSERT [dbo].[KQUA] ([MASV], [MAHP], [DIEM]) VALUES (130303, 4, 5)
INSERT [dbo].[KQUA] ([MASV], [MAHP], [DIEM]) VALUES (130303, 6, 7)
INSERT [dbo].[KQUA] ([MASV], [MAHP], [DIEM]) VALUES (140908, 1, 10)
INSERT [dbo].[KQUA] ([MASV], [MAHP], [DIEM]) VALUES (140908, 2, 9)
INSERT [dbo].[KQUA] ([MASV], [MAHP], [DIEM]) VALUES (140908, 3, 8)
INSERT [dbo].[KQUA] ([MASV], [MAHP], [DIEM]) VALUES (140908, 4, 5)
GO

# [dbo].[MHOC]

In [0]:
INSERT [dbo].[MHOC] ([TENMH], [MAMH], [TINCHI], [MAKH]) VALUES (N'Toan Ha Cap', N'Cad100', 3, N'1')
INSERT [dbo].[MHOC] ([TENMH], [MAMH], [TINCHI], [MAKH]) VALUES (N'Toan Super Cao Cap', N'cad1000', 3, N'1')
INSERT [dbo].[MHOC] ([TENMH], [MAMH], [TINCHI], [MAKH]) VALUES (N'Toan Cao Cap', N'cad101', 3, N'1')
INSERT [dbo].[MHOC] ([TENMH], [MAMH], [TINCHI], [MAKH]) VALUES (N'Van Ha Cap', N'vad100', 3, N'2')
INSERT [dbo].[MHOC] ([TENMH], [MAMH], [TINCHI], [MAKH]) VALUES (N'Van Cao Cap', N'vad101', 3, N'2')
INSERT [dbo].[MHOC] ([TENMH], [MAMH], [TINCHI], [MAKH]) VALUES (N'Van Hoc', N'vad123', 3, N'2')
GO

# [dbo].[SVIEN]

In [0]:
INSERT [dbo].[SVIEN] ([TEN], [MASV], [NAM], [MAKH], [NAMSINH], [GIOITINH]) VALUES (N'Tran Hoang', 123456, 2, N'2', CAST(N'1999-01-01' AS Date), NULL)
INSERT [dbo].[SVIEN] ([TEN], [MASV], [NAM], [MAKH], [NAMSINH], [GIOITINH]) VALUES (N'Nguyen Tran', 130303, 1, N'1', CAST(N'2000-01-01' AS Date), NULL)
INSERT [dbo].[SVIEN] ([TEN], [MASV], [NAM], [MAKH], [NAMSINH], [GIOITINH]) VALUES (N'Nguyen Long', 140908, 1, N'1', CAST(N'2000-02-02' AS Date), NULL)
INSERT [dbo].[SVIEN] ([TEN], [MASV], [NAM], [MAKH], [NAMSINH], [GIOITINH]) VALUES (N'Nguyen And', 140909, 1, N'1', CAST(N'2001-01-01' AS Date), NULL)
GO

# [FK_DKIEN_MAMH]

In [0]:
ALTER TABLE [dbo].[DKIEN]  WITH CHECK ADD  CONSTRAINT [FK_DKIEN_MAMH] FOREIGN KEY([MAMH])
REFERENCES [dbo].[MHOC] ([MAMH])
GO
ALTER TABLE [dbo].[DKIEN] CHECK CONSTRAINT [FK_DKIEN_MAMH]
GO

# [FK_HPHAN_MAMH]

In [0]:
ALTER TABLE [dbo].[HPHAN]  WITH CHECK ADD  CONSTRAINT [FK_HPHAN_MAMH] FOREIGN KEY([MAMH])
REFERENCES [dbo].[MHOC] ([MAMH])
GO
ALTER TABLE [dbo].[HPHAN] CHECK CONSTRAINT [FK_HPHAN_MAMH]
GO

# [FK_KQUA_MAHP]

In [0]:
ALTER TABLE [dbo].[KQUA]  WITH CHECK ADD  CONSTRAINT [FK_KQUA_MAHP] FOREIGN KEY([MAHP])
REFERENCES [dbo].[HPHAN] ([MAHP])
GO
ALTER TABLE [dbo].[KQUA] CHECK CONSTRAINT [FK_KQUA_MAHP]
GO

# [FK_KQUA_MASV]

In [0]:
ALTER TABLE [dbo].[KQUA]  WITH CHECK ADD  CONSTRAINT [FK_KQUA_MASV] FOREIGN KEY([MASV])
REFERENCES [dbo].[SVIEN] ([MASV])
GO
ALTER TABLE [dbo].[KQUA] CHECK CONSTRAINT [FK_KQUA_MASV]
GO

# [FK_MHOC_MAKH]

In [0]:
ALTER TABLE [dbo].[MHOC]  WITH CHECK ADD  CONSTRAINT [FK_MHOC_MAKH] FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHOA] ([MAKHOA])
GO
ALTER TABLE [dbo].[MHOC] CHECK CONSTRAINT [FK_MHOC_MAKH]
GO

# [FK_SVIEN_MAKHOA]

In [0]:
ALTER TABLE [dbo].[SVIEN]  WITH CHECK ADD  CONSTRAINT [FK_SVIEN_MAKHOA] FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHOA] ([MAKHOA])
GO
ALTER TABLE [dbo].[SVIEN] CHECK CONSTRAINT [FK_SVIEN_MAKHOA]
GO

# [CK__KQUA__DIEM__32E0915F]

In [0]:
ALTER TABLE [dbo].[KQUA]  WITH CHECK ADD CHECK  (([DIEM]>=(0) AND [DIEM]<=(10)))
GO

# [CK__SVIEN__NAM__267ABA7A]

In [0]:
ALTER TABLE [dbo].[SVIEN]  WITH CHECK ADD CHECK  (([NAM]>=(1) AND [NAM]<=(4)))
GO

# [QLSVien]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [QLSVien] SET  READ_WRITE 
GO